Sprint 2/step 2
chernyshevdi/react-burger pull request #4
Opened 2021-12-07 01:38 UTC by chernyshevdi

2021-12-07 17:31 UTC, grishbar commented
`надо исправить`
Добрый вечер, обратите внимание на 4 пункт в задании - 
4. Доработка интерфейса навигации по ингредиентам
В компоненте BurgerIngredients есть три переключателя: «Булки», «Соусы» и «Начинки». Используйте эти переключатели как панель навигации. По мере пользовательского скролла ингредиентов в компоненте BurgerIngredients выделяйте активным тот переключатель, заголовок которого в самом контейнере ближе всего к верхней левой границе контейнера компонента BurgerIngredients.

2021-12-07 18:02 UTC, chernyshevdi commented
А можно поподробнее, что с переключателями не так?

2021-12-07 18:45 UTC, grishbar requested changes
Отличная работа, весь запрашиваемый функционал работает корректно, код чистый и легко читается, круто что воспользовался useCallback, написал усилители для запросов и нигде в редакс не забыл про дефолтную обработку экшенов и деструктуризацию state. Есть несколько моментов, которые надо исправить, чтобы принять работу:

- [x] Переименовать некорректно названные переменные
- [ ] Избавиться от react контекста, перейти полностью на redux
- [x] Переименовать не совсем удачно названные переменные
- [ ] Обработать статус ответа при запроса на бэкенд
- [ ] Поправить, состояние которое принимает твое хранилище при неудачном запросе
- [ ] Избавиться от библиотек, которые не используешь

2021-12-07 18:45 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +},[ingredientsInBurgerConstructor.other, dispatch])
`надо исправить`
вся логика работы с данными в хранилище должна производиться внутри reducerа, тут только dispatchишь actionы

2021-12-07 18:45 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +function debounce(func, wait, immediate) {
`отлично`
прикольная идея с debounce мне нравится

2021-12-07 18:45 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +          }) : null }
`можно лучше`
тернарник тут излишний и так как ты мапишься по массиву, можно вобще без условия рендерить

2021-12-07 18:45 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +              isLocked={true}
`можно лучше`
можно просто isLocked

2021-12-07 18:45 UTC, grishbar commented on src/components/product-item/product-item.js
> +    }
`можно лучше`
тут намного лучше подходит reduce

2021-12-07 18:45 UTC, grishbar commented on src/services/actions/burger-constructor.jsx
> +        })
`надо исправить`
также тут надо проверить, что результат который приходит [пришел со статус кодом 2xx](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

2021-12-07 18:45 UTC, grishbar commented on src/services/actions/burger-ingredients.jsx
> +            if(res) {
[тут тоже](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

2021-12-07 18:45 UTC, grishbar commented on src/services/reducers/app.jsx
> +        }
`можно лучше`
по сути у тебя тут одно свойство в объекте, которое всегда меняется, так, что можно обойтись без деструктуризации state

2021-12-07 18:45 UTC, grishbar commented on src/services/reducers/burger-constructor.jsx
> +    ingredientsInBurgerConstructor: {bun:[], other:[]}, //список всех ингредиентов в текущем конструкторе бургера
`можно лучше`
на мой взгля хранить ингредиенты булок и остальных отдельно излишне, намного красивее и чище код будет, если все ингредиенты будешь хранить в одном месте

2021-12-07 18:45 UTC, grishbar commented on src/services/reducers/burger-constructor.jsx
> +                    other:[...state.ingredientsInBurgerConstructor.other, action.item]
`можно лучше`
тебе с бэкнеда приходят ингредиенты с типом bun и main логично, что у себя ты их будешь хранить также

2021-12-07 18:45 UTC, grishbar commented on src/services/reducers/burger-constructor.jsx
> +        }
`монжно лучше`
название action не очень отражает, что оно делает в действительности, и логика перемещения ингредиента должна быть описана здесь,

2021-12-07 18:45 UTC, grishbar commented on src/services/reducers/burger-ingredients.jsx
> +        }
`надо исправить`
если запрос за данными падает, надо возвращать:
```
...initialState,
ingredientsFailed: true,
```

2021-12-07 18:45 UTC, grishbar commented on src/services/reducers/reducer.jsx
> +
`надо исправить`
удалить этот файл, если не нужен, все комментарии, которые не документируют код должны быть удалены, даже если кажется, что когда нибудь спрятанный в комментариях код может понадобиться, так как когда действитльно такой момент настает, даже не вспомнишь, что подобный код уже где то написан, но при этом при чтении кода, постоянно будешь натыкаться на эти комментарии

2021-12-07 18:47 UTC, grishbar commented
> 

Извини, с переключателями все верно сделано, можешь еще доработать, чтобы при клике был скролл и будет вобще прекрасно, но это не обязательно

2021-12-10 04:02 UTC, grishbar requested changes
Прости, что сразу не написал, обрати пожалуйста внимание, на то, как ты работаешь с хранилищем, отписал комментарии с пометкой "надо исправить", поправь, все согласно им пожалуйста

2021-12-10 04:02 UTC, grishbar commented on src/services/reducers/burger-constructor.jsx
> +        case DELETE_BURGERCONSTRUCTOR_DATA: {
`надо исправить`
слово DATA в типах экшенов везде излишнее не добавляет никакой нагрузки, и ты удаляешь ингредиент а не BURGERCONSTRUCTOR_DATA так, что тут тоже надо бы переименовать

2021-12-10 04:02 UTC, grishbar commented on src/services/reducers/burger-constructor.jsx
> +               // ...state.ingredientsInBurgerConstructor.other.splice(action.hoverIndex, 0, state.dragItem)
`надо исправить` комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2021-12-10 21:11 UTC, grishbar approved these changes
Прекрасно, все критичные моменты исправил, работу засчитываю

2021-12-10 21:11 UTC, grishbar commented on src/services/actions/burger-constructor.jsx
> +            console.log(err)
`надо исправить`
тут тоже надо экшен отвечаюший за ошибку отправить

2022-01-16 19:16 UTC, merged